spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 465
    username: damolacoker@gmail.com
    password: bxutfdkrqzqojyyw
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true

server:
  port: 8106


# Ribbon config
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

logging:
  file: notification-service.log