spring:
  application:
    name: db-service
  data:
    mongodb:
      database: finche
      port: 5006

server:
  port: 8102


# Ribbon config
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

logging:
  file: db-service.log

