spring:
  application:
    name: db-service
  data:
    mongodb:
      database: finche
      port: 5006

server:
  servlet:
    context-path: /db
  port: 8102


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


