spring:
  application:
    name: login-service

server:
  servlet:
    context-path: /auth
  port: 8103


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost